# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('system', models.CharField(max_length=50, verbose_name='System')),
                ('ram', models.IntegerField(verbose_name='Ram')),
                ('quote', models.IntegerField(verbose_name='Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Komenda',
                'verbose_name_plural': 'Komendy',
            },
        ),
    ]
